# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: BuildBicep  
  displayName: Build CLI

  strategy:
    matrix:
      windows:
        os: 'windows-latest'
        rid: 'win-x64'
        configuration: 'release'
        publishLanguageServer: 'false'
      linux:
        os: 'ubuntu-latest'
        rid: 'linux-x64'
        configuration: 'release'
        publishLanguageServer: 'true'
      mac:
        os: 'macOS-latest'
        rid: 'osx-x64'
        configuration: 'release'
        publishLanguageServer: 'false'

  pool:
    vmImage: $(os)

  steps:
  - task: UseDotNet@2
    displayName: Setup .NET Core
    inputs:
      packageType: sdk
      version: 3.1.301
      installationPath: $(Agent.TempDirectory)/dotnet
  
  - script: dotnet build --configuration $(configuration)
    displayName: Build
  
  - script: dotnet test --configuration $(configuration) --collect:"XPlat Code Coverage" --settings ./.github/workflows/codecov.runsettings
    displayName: Test
  
  - script: dotnet publish --configuration $(configuration) ./src/Bicep.LangServer/Bicep.LangServer.csproj
    displayName: Publish Language Server
    condition: eq(variables.configuration, true)

  - script: dotnet publish --configuration $(configuration) --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -r $(rid) ./src/Bicep.Cli/Bicep.Cli.csproj
    displayName: Publish Bicep
